//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1891
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "8.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HintInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HintInfo() {
        }
        
        /// <summary>
        ///   返回此类使用的、缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HintInfo", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为所有资源查找重写当前线程的 CurrentUICulture 属性，
        ///   方法是使用此强类型资源类。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找与  account. 类似的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Adult 类似的本地化字符串。
        /// </summary>
        internal static string Adult {
            get {
                return ResourceManager.GetString("Adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The age is bigger than 11. 类似的本地化字符串。
        /// </summary>
        internal static string AgeBigger {
            get {
                return ResourceManager.GetString("AgeBigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Since your departure date is within 3 days, pls call 1-(888)-288-7528 for your booking. Thank You!! 类似的本地化字符串。
        /// </summary>
        internal static string AirDateError {
            get {
                return ResourceManager.GetString("AirDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与  and Password is  类似的本地化字符串。
        /// </summary>
        internal static string AndIs {
            get {
                return ResourceManager.GetString("AndIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 As it is impossible for us to retrieve your original password we have generated a new one. 类似的本地化字符串。
        /// </summary>
        internal static string AsOne {
            get {
                return ResourceManager.GetString("AsOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Birthday 类似的本地化字符串。
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 birthday format error. 类似的本地化字符串。
        /// </summary>
        internal static string BirthdayError {
            get {
                return ResourceManager.GetString("BirthdayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Booking failed. 类似的本地化字符串。
        /// </summary>
        internal static string BookingFailed {
            get {
                return ResourceManager.GetString("BookingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 You selected flight is invalid.&amp;nbsp;&amp;nbsp; Please re-search or call our experienced Sale Agents at  类似的本地化字符串。
        /// </summary>
        internal static string BookingTicketFailure {
            get {
                return ResourceManager.GetString("BookingTicketFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Booking Time 类似的本地化字符串。
        /// </summary>
        internal static string BookingTime {
            get {
                return ResourceManager.GetString("BookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Business class seats may not avaialbe for short haul flights due to aircraft configuration. 类似的本地化字符串。
        /// </summary>
        internal static string BusinessClassWarnMessage {
            get {
                return ResourceManager.GetString("BusinessClassWarnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Cabin / Class 类似的本地化字符串。
        /// </summary>
        internal static string CabinClass {
            get {
                return ResourceManager.GetString("CabinClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Sorry, can not booking the routing.  please choose others routing again. 类似的本地化字符串。
        /// </summary>
        internal static string CanNotBooking {
            get {
                return ResourceManager.GetString("CanNotBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Sorry, the selected flight has been sold out, please select other flight to continue. 类似的本地化字符串。
        /// </summary>
        internal static string CannotBookMsg {
            get {
                return ResourceManager.GetString("CannotBookMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Case Number 类似的本地化字符串。
        /// </summary>
        internal static string CaseNumber {
            get {
                return ResourceManager.GetString("CaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 ChangeFlightType 类似的本地化字符串。
        /// </summary>
        internal static string ChangeFlightType {
            get {
                return ResourceManager.GetString("ChangeFlightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please check your current password. 类似的本地化字符串。
        /// </summary>
        internal static string CheckPassword {
            get {
                return ResourceManager.GetString("CheckPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Child 类似的本地化字符串。
        /// </summary>
        internal static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The confirmation e-mail will be sent out within 3 business days. 类似的本地化字符串。
        /// </summary>
        internal static string ConfirmationEmail {
            get {
                return ResourceManager.GetString("ConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Date 类似的本地化字符串。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Dear  类似的本地化字符串。
        /// </summary>
        internal static string Dear {
            get {
                return ResourceManager.GetString("Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Dep. Date 类似的本地化字符串。
        /// </summary>
        internal static string DepDate {
            get {
                return ResourceManager.GetString("DepDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Airline names, flight numbers, and exact departure &amp; arrival time will be displayed later after entering traveller&apos;s information. 类似的本地化字符串。
        /// </summary>
        internal static string DISP_MESSAGE {
            get {
                return ResourceManager.GetString("DISP_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Email Address entered is already in use. Choose another. 类似的本地化字符串。
        /// </summary>
        internal static string EmailAnother {
            get {
                return ResourceManager.GetString("EmailAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The e-mail address you provided was not recognized. Please try again. 类似的本地化字符串。
        /// </summary>
        internal static string EmailNotRrecognized {
            get {
                return ResourceManager.GetString("EmailNotRrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please input your account 类似的本地化字符串。
        /// </summary>
        internal static string EmptyID {
            get {
                return ResourceManager.GetString("EmptyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please input your password 类似的本地化字符串。
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter your address to receive our travel packs exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter Birthday exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterBirthday {
            get {
                return ResourceManager.GetString("EnterBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter City exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterCity {
            get {
                return ResourceManager.GetString("EnterCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter phone(daytime) exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterDPhone {
            get {
                return ResourceManager.GetString("EnterDPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter First name exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterFirst {
            get {
                return ResourceManager.GetString("EnterFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter Last name exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterLast {
            get {
                return ResourceManager.GetString("EnterLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter Password exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter Zip/Postal Code exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterPostal {
            get {
                return ResourceManager.GetString("EnterPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter verity password exactly as it appears on ID card or passport. 类似的本地化字符串。
        /// </summary>
        internal static string EnterVerity {
            get {
                return ResourceManager.GetString("EnterVerity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The search condition has been removed from cache, please re-search. 类似的本地化字符串。
        /// </summary>
        internal static string err1 {
            get {
                return ResourceManager.GetString("err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Departure date is greater than the current date seven days 类似的本地化字符串。
        /// </summary>
        internal static string err10 {
            get {
                return ResourceManager.GetString("err10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 We can only accept dates that occur between 类似的本地化字符串。
        /// </summary>
        internal static string err11 {
            get {
                return ResourceManager.GetString("err11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 and 12/27/2008. Please enter a new date. 类似的本地化字符串。
        /// </summary>
        internal static string err12 {
            get {
                return ResourceManager.GetString("err12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 We found no matches for 类似的本地化字符串。
        /// </summary>
        internal static string err13 {
            get {
                return ResourceManager.GetString("err13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The mail address pattern is wrong 类似的本地化字符串。
        /// </summary>
        internal static string err14 {
            get {
                return ResourceManager.GetString("err14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 are you sure? 类似的本地化字符串。
        /// </summary>
        internal static string err2 {
            get {
                return ResourceManager.GetString("err2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please read Terms &amp; Conditions, And cancels elects 类似的本地化字符串。
        /// </summary>
        internal static string err3 {
            get {
                return ResourceManager.GetString("err3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Searching is not available in Web Searching now. Please choose another travel date or destination. 类似的本地化字符串。
        /// </summary>
        internal static string err4 {
            get {
                return ResourceManager.GetString("err4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The check-in date must occur after the today date. Please change the date 类似的本地化字符串。
        /// </summary>
        internal static string err5 {
            get {
                return ResourceManager.GetString("err5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The check-out date must occur after the check-in date. Please change the date 类似的本地化字符串。
        /// </summary>
        internal static string err6 {
            get {
                return ResourceManager.GetString("err6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The Depart date must occur after the Return date. Please change the date 类似的本地化字符串。
        /// </summary>
        internal static string err7 {
            get {
                return ResourceManager.GetString("err7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The Return date must occur after the check-out date. Please change the date 类似的本地化字符串。
        /// </summary>
        internal static string err8 {
            get {
                return ResourceManager.GetString("err8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Return date is greater than the current date seven days 类似的本地化字符串。
        /// </summary>
        internal static string err9 {
            get {
                return ResourceManager.GetString("err9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Error Message. 类似的本地化字符串。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Flight No 类似的本地化字符串。
        /// </summary>
        internal static string FlightNo {
            get {
                return ResourceManager.GetString("FlightNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 First Name format error. 类似的本地化字符串。
        /// </summary>
        internal static string FNError {
            get {
                return ResourceManager.GetString("FNError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Origin/Destination can not be booked online, please call our sales agent for booking. 类似的本地化字符串。
        /// </summary>
        internal static string ForbiddenAirport {
            get {
                return ResourceManager.GetString("ForbiddenAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与  FOR DETAIL 类似的本地化字符串。
        /// </summary>
        internal static string FORDETAIL {
            get {
                return ResourceManager.GetString("FORDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Origin/Destination can not be booked online, please call our sales agent for booking. 类似的本地化字符串。
        /// </summary>
        internal static string HasForbiddenAirport {
            get {
                return ResourceManager.GetString("HasForbiddenAirport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Airport Overnight Stay 类似的本地化字符串。
        /// </summary>
        internal static string HasOverNightStay {
            get {
                return ResourceManager.GetString("HasOverNightStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 has been compeleted successfully. 类似的本地化字符串。
        /// </summary>
        internal static string hasSuccessfully {
            get {
                return ResourceManager.GetString("hasSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Since your check-in date is earlier than our specified dates, please call our Sale Agent direclty for bookings. please call 1-(888)-288-7528 类似的本地化字符串。
        /// </summary>
        internal static string Hotel_Date_Error1 {
            get {
                return ResourceManager.GetString("Hotel_Date_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Since your check-in date is earlier than our specified dates, please call our Sale Agent direclty for bookings. please call 1-(888)-288-7528 类似的本地化字符串。
        /// </summary>
        internal static string Hotel_Date_Error2 {
            get {
                return ResourceManager.GetString("Hotel_Date_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Departure Date must be greater than Check-in date. 类似的本地化字符串。
        /// </summary>
        internal static string Hotel_Date_Error3 {
            get {
                return ResourceManager.GetString("Hotel_Date_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The check-in date must occur after the today date. Please change the date. 类似的本地化字符串。
        /// </summary>
        internal static string Hotel_Date_Error4 {
            get {
                return ResourceManager.GetString("Hotel_Date_Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The check-out date must occur after the check-in date. Please change the date. 类似的本地化字符串。
        /// </summary>
        internal static string Hotel_Date_Error5 {
            get {
                return ResourceManager.GetString("Hotel_Date_Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter the correct city name or Code 类似的本地化字符串。
        /// </summary>
        internal static string Hotel_Error_City {
            get {
                return ResourceManager.GetString("Hotel_Error_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Invalid email, Please try again 类似的本地化字符串。
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Invalid password, Please try again 类似的本地化字符串。
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Invaluable search condition. 类似的本地化字符串。
        /// </summary>
        internal static string InvaluableSearch {
            get {
                return ResourceManager.GetString("InvaluableSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 This booking class seats have been sold out, the original quoted price is increased by ${0}, do you want to continue? 类似的本地化字符串。
        /// </summary>
        internal static string LargeChangedSoldoutMsg {
            get {
                return ResourceManager.GetString("LargeChangedSoldoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Leaves / Arrives 类似的本地化字符串。
        /// </summary>
        internal static string LeavesArrives {
            get {
                return ResourceManager.GetString("LeavesArrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Due to airfare changes by airlines, the original quoted price is increased by ${0}, do you want to continue? 类似的本地化字符串。
        /// </summary>
        internal static string LittleChangedSoldoutMsg {
            get {
                return ResourceManager.GetString("LittleChangedSoldoutMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Last Name format error. 类似的本地化字符串。
        /// </summary>
        internal static string LSError {
            get {
                return ResourceManager.GetString("LSError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Meal 类似的本地化字符串。
        /// </summary>
        internal static string Meal {
            get {
                return ResourceManager.GetString("Meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Name Passenger 类似的本地化字符串。
        /// </summary>
        internal static string NamePassenger {
            get {
                return ResourceManager.GetString("NamePassenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The new login name is 类似的本地化字符串。
        /// </summary>
        internal static string NewLogin {
            get {
                return ResourceManager.GetString("NewLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与  next time. Note that the password is case-sensitive. 类似的本地化字符串。
        /// </summary>
        internal static string NextTime {
            get {
                return ResourceManager.GetString("NextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 No Available Flight. 类似的本地化字符串。
        /// </summary>
        internal static string NoAvailableFlight {
            get {
                return ResourceManager.GetString("NoAvailableFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please finish your search conditions. 类似的本地化字符串。
        /// </summary>
        internal static string NoSearchConditions {
            get {
                return ResourceManager.GetString("NoSearchConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Some portions of your order are not confirmed yet. 类似的本地化字符串。
        /// </summary>
        internal static string NotConfirmed {
            get {
                return ResourceManager.GetString("NotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Note that this is an automatically generated e-mail, please do not reply to this e-mail address. 类似的本地化字符串。
        /// </summary>
        internal static string NoteAddress {
            get {
                return ResourceManager.GetString("NoteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 If you do not hear back from us within 3 business days, pls call us at 1-(888)-288-7528. 类似的本地化字符串。
        /// </summary>
        internal static string NotHearMsg {
            get {
                return ResourceManager.GetString("NotHearMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The Account you entered does not  exist or is incorrect 类似的本地化字符串。
        /// </summary>
        internal static string NoThisAccount {
            get {
                return ResourceManager.GetString("NoThisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 OP Status 类似的本地化字符串。
        /// </summary>
        internal static string OPStatus {
            get {
                return ResourceManager.GetString("OPStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Departure date is greater than the current date seven days. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error1 {
            get {
                return ResourceManager.GetString("Package_Date_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Return date is greater than the current date seven days. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error2 {
            get {
                return ResourceManager.GetString("Package_Date_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Departure date is greater than the current date seven days. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error3 {
            get {
                return ResourceManager.GetString("Package_Date_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Return date is greater than the current date seven days. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error4 {
            get {
                return ResourceManager.GetString("Package_Date_Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The check-in date must occur after the today date. Please change the date. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error5 {
            get {
                return ResourceManager.GetString("Package_Date_Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The check-out date must occur after the check-in date. Please change the date. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error6 {
            get {
                return ResourceManager.GetString("Package_Date_Error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The Depart date must occur after the Return date. Please change the date. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error7 {
            get {
                return ResourceManager.GetString("Package_Date_Error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The check-in date must occur after the Depart date. Please change the date. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error8 {
            get {
                return ResourceManager.GetString("Package_Date_Error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The Return date must occur after the check-out date. Please change the date. 类似的本地化字符串。
        /// </summary>
        internal static string Package_Date_Error9 {
            get {
                return ResourceManager.GetString("Package_Date_Error9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter the correct From city name or Code 类似的本地化字符串。
        /// </summary>
        internal static string Package_Error_City1 {
            get {
                return ResourceManager.GetString("Package_Error_City1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter the correct To city name or Code 类似的本地化字符串。
        /// </summary>
        internal static string Package_Error_City2 {
            get {
                return ResourceManager.GetString("Package_Error_City2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 We found no matches for from city or airport 类似的本地化字符串。
        /// </summary>
        internal static string Package_Error_City3 {
            get {
                return ResourceManager.GetString("Package_Error_City3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 We found no matches for to city or airport 类似的本地化字符串。
        /// </summary>
        internal static string Package_Error_City4 {
            get {
                return ResourceManager.GetString("Package_Error_City4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Passport Number 类似的本地化字符串。
        /// </summary>
        internal static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The password must be at least 6 or 11 characters long. 类似的本地化字符串。
        /// </summary>
        internal static string PasswordLong {
            get {
                return ResourceManager.GetString("PasswordLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Payment Status 类似的本地化字符串。
        /// </summary>
        internal static string PaymentStatus {
            get {
                return ResourceManager.GetString("PaymentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter Type New Password again. 类似的本地化字符串。
        /// </summary>
        internal static string PleaseAgain {
            get {
                return ResourceManager.GetString("PleaseAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter the same password in both the password boxes. 类似的本地化字符串。
        /// </summary>
        internal static string PleaseBoxes {
            get {
                return ResourceManager.GetString("PleaseBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 PLEASE CALL  类似的本地化字符串。
        /// </summary>
        internal static string PLEASECALL {
            get {
                return ResourceManager.GetString("PLEASECALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please read Terms &amp; Conditions and agree to it first. 类似的本地化字符串。
        /// </summary>
        internal static string PleaseElects {
            get {
                return ResourceManager.GetString("PleaseElects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please enter Old Password. 类似的本地化字符串。
        /// </summary>
        internal static string PleasePassword {
            get {
                return ResourceManager.GetString("PleasePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 please use this when logging in to 类似的本地化字符串。
        /// </summary>
        internal static string PleaseSensitive {
            get {
                return ResourceManager.GetString("PleaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 e.g., promotional travel offers, last minute deals, various tours, hotels, and sweepstakes. 类似的本地化字符串。
        /// </summary>
        internal static string PromotionalSweepstakes {
            get {
                return ResourceManager.GetString("PromotionalSweepstakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Record Locator 类似的本地化字符串。
        /// </summary>
        internal static string RecordLocator {
            get {
                return ResourceManager.GetString("RecordLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 You have requested a password reminder for your  类似的本地化字符串。
        /// </summary>
        internal static string RequestedPassword {
            get {
                return ResourceManager.GetString("RequestedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Routing 类似的本地化字符串。
        /// </summary>
        internal static string Routing {
            get {
                return ResourceManager.GetString("Routing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please select Card Type. 类似的本地化字符串。
        /// </summary>
        internal static string SelectCardType {
            get {
                return ResourceManager.GetString("SelectCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please select city. 类似的本地化字符串。
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please select country or area. 类似的本地化字符串。
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please select state. 类似的本地化字符串。
        /// </summary>
        internal static string SelectState {
            get {
                return ResourceManager.GetString("SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Passenger Name should only contain english character. 类似的本地化字符串。
        /// </summary>
        internal static string ShouldBeEnglishName {
            get {
                return ResourceManager.GetString("ShouldBeEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Sincerely 类似的本地化字符串。
        /// </summary>
        internal static string Sincerely {
            get {
                return ResourceManager.GetString("Sincerely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与  Support Team 类似的本地化字符串。
        /// </summary>
        internal static string SupportTeam {
            get {
                return ResourceManager.GetString("SupportTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Thanks for registering our membership program. 类似的本地化字符串。
        /// </summary>
        internal static string ThanksProgram {
            get {
                return ResourceManager.GetString("ThanksProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 .  You can start enjoying the membership benefits, 类似的本地化字符串。
        /// </summary>
        internal static string TheBenefits {
            get {
                return ResourceManager.GetString("TheBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The new membership number is 类似的本地化字符串。
        /// </summary>
        internal static string TheMembership {
            get {
                return ResourceManager.GetString("TheMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The search condition has been removed from cache, please re-search. 类似的本地化字符串。
        /// </summary>
        internal static string TheResearch {
            get {
                return ResourceManager.GetString("TheResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 The mail address pattern is wrong. 类似的本地化字符串。
        /// </summary>
        internal static string TheWrong {
            get {
                return ResourceManager.GetString("TheWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please select Region 类似的本地化字符串。
        /// </summary>
        internal static string Tour_Error1 {
            get {
                return ResourceManager.GetString("Tour_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please select country or area 类似的本地化字符串。
        /// </summary>
        internal static string Tour_Error2 {
            get {
                return ResourceManager.GetString("Tour_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please select City 类似的本地化字符串。
        /// </summary>
        internal static string Tour_Error3 {
            get {
                return ResourceManager.GetString("Tour_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Please input Departure Date 类似的本地化字符串。
        /// </summary>
        internal static string Tour_Error4 {
            get {
                return ResourceManager.GetString("Tour_Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Since your departure date is within 3 days, pls call 1-(888)-288-7528 for your booking. Thank You!! 类似的本地化字符串。
        /// </summary>
        internal static string Tour_Error5 {
            get {
                return ResourceManager.GetString("Tour_Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Type 类似的本地化字符串。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Unknow Error 类似的本地化字符串。
        /// </summary>
        internal static string UnknowError {
            get {
                return ResourceManager.GetString("UnknowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 View 类似的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与  your new password 类似的本地化字符串。
        /// </summary>
        internal static string YouNPassword {
            get {
                return ResourceManager.GetString("YouNPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Your new password is 类似的本地化字符串。
        /// </summary>
        internal static string YourIs {
            get {
                return ResourceManager.GetString("YourIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Your registration of  类似的本地化字符串。
        /// </summary>
        internal static string YourOf {
            get {
                return ResourceManager.GetString("YourOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找与 Your Account of GTT has been updated successfully. 类似的本地化字符串。
        /// </summary>
        internal static string YourSuccessfully {
            get {
                return ResourceManager.GetString("YourSuccessfully", resourceCulture);
            }
        }
    }
}
